### ISSUE TITLE
docker pull fails when using set-alias to create or move tag

### ISSUE THREAD

**Issue by arthurlogilab** [davedoesdev/dxf#33] opened 2020-07-17 14:59 UTC
We're trying to use dxf to move a tag from a position to another (saying `production` is now the same as `integration`) : 

```
DXF_HOST=*** DXF_USERNAME=*** DXF_PASSWORD=*** dxf set-alias myproject/myproject-builder production $(DXF_HOST=*** DXF_USERNAME=*** DXF_PASSWORD=*** dxf get-alias myproject/myproject-builder integration)
```

It seems to do the job but 

```
docker pull registry/project/image:newtag 
[snip]
invalid character '\x1f' looking for beginning of value
```
The `get-alias` shows the same signatures, but not the `get-digest`... are we missing something

It would be awesome if there was a `dxf set-alias myproject/image:tag myproject/image:newtag` that could do this sort of thing.

**Comment by davedoesdev** [comment] 2020-07-17 19:59
This is a duplicate of https://github.com/davedoesdev/dxf/issues/3 I think.

Per the README:

>Please note that `dxf` does _not_ generate Docker container configuration, so you won't be able to `docker pull` data you store using `dxf`.

Hope that makes sense?

**Comment by davedoesdev** [comment] 2020-07-31 06:57
Closing as duplicate

**Closed by davedoesdev** 2020-07-31 06:57 UTC
